### ISSUE TITLE
LinkedInner Module not Working

### ISSUE THREAD

**Issue by Rosenb90** [superhedgy/AttackSurfaceMapper#13]
Hi,
When trying to use the LinkedInner module in a run I keep getting this error:

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianrosen/AttackSurfaceMapper/modules/linkedinner.py", line 66, in loadPage
    response = client.open(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

[*] Error: Could not authenticate to LinkedIn. object of type 'NoneType' has no len()

Traceback (most recent call last):
  File "ASM.py", line 890, in <module>
    main(keychain,sw1,output_path,c1)
  File "ASM.py", line 708, in main
    linkedinner.get_emails_for_company_name(switch,target_list[key],keychain["linkedin_username"],keychain["linkedin_password"],answer2,0)
  File "/Users/brianrosen/AttackSurfaceMapper/modules/linkedinner.py", line 83, in get_emails_for_company_name
    cookies['JSESSIONID'] = 'ajax:0397788525211216808'
TypeError: 'NoneType' object does not support item assignment`

Thanks for any help!

**Comment by ojensen5115** [comment]
It looks like your primary problem is:
 `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>`

Are you on a mac? See https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org for instructions on how to get urllib to work with ssl certs.

**Comment by Rosenb90** [comment]
That worked. Thank you so much for your help!
