### ISSUE TITLE
Could not authenticate to LinkedIn

### ISSUE THREAD

**Issue by Jacksole** [superhedgy/AttackSurfaceMapper#32]
Hello I'm trying to use this tool but I get this error message when I try to use it:

```
[*] Error: Could not authenticate to LinkedIn. cannot use a string pattern on a bytes-like object

Traceback (most recent call last):
  File "asm.py", line 941, in <module>
    main(keychain, sw1, output_path, c1)
  File "asm.py", line 745, in main
    keychain["linkedin_password"], answer2, 0)
  File "/home/username/Projects/Github/OSINT/AttackSurfaceMapper/modules/linkedinner.py", line 93, in get_emails_for_company_name
    cookies['JSESSIONID'] = 'ajax:0397788525211216808'
TypeError: 'NoneType' object does not support item assignment
```

**Comment by superhedgy** [comment]
I wasn't able to replicate this issue. I will have to conclude that is related with your LinkedIn account. 

Please make sure 2-FA is disable before using the tool.

**Comment by Jacksole** [comment]
Thanks, I'll do that
