### ISSUE TITLE
Linkedin authentcation fail even with correct user/pass

### ISSUE THREAD

**Issue by dinvisible1** [superhedgy/AttackSurfaceMapper#37]
[*] Error: Could not authenticate to LinkedIn. cannot use a string pattern on a bytes-like object

Traceback (most recent call last):
  File "asm.py", line 951, in <module>
    main(keychain, sw1, output_path, c1)
  File "asm.py", line 756, in main
    keychain["linkedin_password"], answer2, 0)
  File "/root/AttackSurfaceMapper/modules/linkedinner.py", line 93, in get_emails_for_company_name
    cookies['JSESSIONID'] = 'ajax:0397788525211216808'
TypeError: 'NoneType' object does not support item assignment

**Comment by VirenMohindra** [comment]
+1
