### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 0xskywalker** [superhedgy/AttackSurfaceMapper#8]
Traceback (most recent call last):
  File "ASM.py", line 890, in <module>
    main(keychain,sw1,output_path,c1)
  File "ASM.py", line 623, in main
    if (add_target_ip(target_list,line) == False):
  File "ASM.py", line 384, in add_target_ip
    add_target_domain(list,domain,validated_input)
  File "ASM.py", line 356, in add_target_domain
    if t.primary_domain in list.keys():
AttributeError: type object 'list' has no attribute 'keys'

A syntax error is in the code, list data structures don't use the keys() method, only dict does.

**Comment by jeffmaley** [comment]
I'm getting the same issue. I can take a look at updating the project, if that's acceptable.

**Comment by martialhax** [comment]
[i] AttackSurfaceMapper is running. . .

Traceback (most recent call last):
  File "asm.py", line 946, in <module>
    main(keychain, sw1, output_path, c1)
  File "asm.py", line 655, in main
    if not add_target_ip(target_list, line):
  File "asm.py", line 413, in add_target_ip
    add_target_domain(list, domain, validated_input)
  File "asm.py", line 384, in add_target_domain
    if t.primary_domain in list_domain.keys():
AttributeError: type object 'list' has no attribute 'keys'

Just cloned and I'm getting as well...
